sudo: required
services:
  - docker

before_install:
  - docker build -t qvvg/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run qvvg/react-test npm test -- --coverage

after_success:
  # build images
  - docker build -t qvvg/multi-client ./client
  - docker build -t qvvg/multi-nginx ./nginx
  - docker build -t qvvg/multi-server ./server
  - docker build -t qvvg/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to dockerhub
  - docker push qvvg/multi-client
  - docker push qvvg/multi-nginx
  - docker push qvvg/multi-server
  - docker push qvvg/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: us-west-2
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-us-west-2-053743197263
#   bucket_path: multi-docker
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY
